CREATE TABLE users (id uuid PRIMARY KEY, email text UNIQUE NOT NULL, name text NOT NULL, password_hash text NOT NULL, role text NOT NULL CHECK(role IN ('CUSTOMER','STAFF','ADMIN')), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sessions (id_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), csrf text NOT NULL, expires_at timestamptz NOT NULL);
CREATE INDEX sessions_user ON sessions(user_id);
CREATE TABLE events (id uuid PRIMARY KEY,title text NOT NULL, venue text NOT NULL, city text NOT NULL, description text NOT NULL, starts_at timestamptz NOT NULL, published boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE event_staff(event_id uuid REFERENCES events(id),user_id uuid REFERENCES users(id),PRIMARY KEY(event_id,user_id));
CREATE TABLE bookings (id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id),event_id uuid NOT NULL REFERENCES events(id),state text NOT NULL CHECK(state IN ('HELD','EXPIRED','CONFIRMED','CANCELLED')),total integer NOT NULL CHECK(total>0),currency text NOT NULL DEFAULT 'BDT' CHECK(currency='BDT'),expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),confirmed_at timestamptz,cancelled_at timestamptz, checked_in_at timestamptz, checked_in_by uuid REFERENCES users(id),ticket_token text UNIQUE);
CREATE INDEX bookings_user_page ON bookings(user_id,created_at DESC,id);
CREATE INDEX bookings_expiry ON bookings(expires_at) WHERE state='HELD';
CREATE TABLE seats (id uuid PRIMARY KEY,event_id uuid NOT NULL REFERENCES events(id),row_label text NOT NULL,number integer NOT NULL CHECK(number>0),tier text NOT NULL,price integer NOT NULL CHECK(price>0),booking_id uuid REFERENCES bookings(id),UNIQUE(event_id,row_label,number));
CREATE INDEX seats_event ON seats(event_id,row_label,number);
CREATE TABLE booking_items (booking_id uuid REFERENCES bookings(id),seat_id uuid REFERENCES seats(id),label text NOT NULL,price integer NOT NULL CHECK(price>0),PRIMARY KEY(booking_id,seat_id));
CREATE TABLE idempotency (user_id uuid REFERENCES users(id),key text NOT NULL,fingerprint text NOT NULL,booking_id uuid NOT NULL REFERENCES bookings(id),PRIMARY KEY(user_id,key));
CREATE TABLE payments (id uuid PRIMARY KEY,booking_id uuid UNIQUE NOT NULL REFERENCES bookings(id),state text NOT NULL CHECK(state IN ('CREATED','SUCCEEDED','FAILED','REFUNDED')),amount integer NOT NULL CHECK(amount>0),currency text NOT NULL DEFAULT 'BDT',provider text NOT NULL DEFAULT 'sandbox',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE webhook_events (id text PRIMARY KEY,fingerprint text NOT NULL,payment_id uuid NOT NULL REFERENCES payments(id),received_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE refunds(id uuid PRIMARY KEY,payment_id uuid UNIQUE NOT NULL REFERENCES payments(id),booking_id uuid NOT NULL REFERENCES bookings(id),state text NOT NULL CHECK(state IN ('PENDING','COMPLETED')),reason text NOT NULL,amount integer NOT NULL CHECK(amount>0),created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz);
CREATE TABLE audit(id bigserial PRIMARY KEY,booking_id uuid NOT NULL REFERENCES bookings(id),actor_id uuid REFERENCES users(id),action text NOT NULL,detail jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_booking ON audit(booking_id,id);
CREATE TABLE outbox(id uuid PRIMARY KEY,type text NOT NULL,payload jsonb NOT NULL,processed_at timestamptz,attempts integer NOT NULL DEFAULT 0,last_error text,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX outbox_pending ON outbox(created_at) WHERE processed_at IS NULL;
CREATE TABLE notifications(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id),booking_id uuid NOT NULL REFERENCES bookings(id),message text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
